apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: polus-volume
  name: polus-volume
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: polus-volume
    spec:
      containers:
      - image: labshare/polus-volume-viewer:0.0.1
        name: polus-volume
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /neuroglancer/data/WIPP-plugins
          name: precomputed
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - name: precomputed
        persistentVolumeClaim:
          claimName: wippdata-pvc
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
